"""Core agent runtime.

This module exposes a single entry point, :func:`run_agent`, which
accepts a prompt and a set of permissions and returns a response
generated by the agent along with audit log entries.  The runtime
delegates planning to :mod:`sentinel_agents.agent.planner` and
execution to :mod:`sentinel_agents.agent.executor`.

This is a very simple implementation intended for demonstration
purposes.  In a real system you would likely use a large language
model (LLM) to plan and choose tools.  Here we instead use a
rudimentary keyword based planner defined in :mod:`planner`.
"""

from __future__ import annotations

from typing import Any, Dict, List, Tuple

from . import planner
from . import executor
from ..policy.policy_engine import PolicyEngine


def run_agent(prompt: str, agent_name: str, permissions: List[str], policy: PolicyEngine) -> Dict[str, Any]:
    """Execute an agent request.

    Parameters
    ----------
    prompt: str
        The user’s natural language request to the agent.
    agent_name: str
        A human readable identifier for the agent (e.g. ``"researcher"``).
    permissions: List[str]
        A list of capability names the agent is allowed to call.
    policy: PolicyEngine
        The policy engine used to approve or deny tool invocations.

    Returns
    -------
    dict
        A dictionary with two keys:

        ``"answer"``
            A string containing the agent’s final answer.
        ``"logs"``
            A list of audit log entries representing each tool call.
    """
    logs: List[Dict[str, Any]] = []
    answer_parts: List[str] = []

    # For simplicity we allow only a fixed number of steps.
    max_steps = 3
    remaining_steps = max_steps
    current_prompt = prompt

    while remaining_steps > 0:
        remaining_steps -= 1
        # Plan which tool to call and with what arguments.
        tool_name, tool_args = planner.decide_tool(current_prompt, permissions)
        if tool_name is None:
            # No more tool calls needed; return accumulated answer.
            break
        # Use the executor to evaluate risk, enforce policy and run the tool.
        result, log_entry = executor.execute_with_policy(agent_name, tool_name, tool_args, policy)
        logs.append(log_entry)
        if not log_entry.get("allowed", False):
            # Denied tool calls stop the agent.
            answer_parts.append(f"[Denied {tool_name}: {log_entry['reason']}]")
            break
        # Append result to answer.
        if result:
            answer_parts.append(str(result))
        # In this simple implementation we stop after one successful call.
        break

    answer = "\n".join(answer_parts) if answer_parts else ""
    return {"answer": answer, "logs": logs}
